#!/usr/bin/env bash
#
# This test will attempt to encrypt and decrypt files to a directory or
# directories themselves.  All tests should fail with specific errors,
# as sources and destinations must be files, not directories.
#

# Get the AES Crypt binary
AESCRYPT="$1"

# See if the current locale uses UTF-8 for encoding
lc_type_enc=$(locale | grep ^LC_CTYPE | sed 's/.*="//' | sed 's/".*//' | \
              sed 's/.*\.//' | tr '[a-z]' '[A-Z]')
if [ "$lc_type_enc" != "UTF-8" ] ; then
    # Current locale doesn't use UTF-8, so try forcing C.UTF-8
    export LANG=C.UTF-8
fi

# Ensure this is not an empty string
if [ -z "$AESCRYPT" ] ; then
    echo "First argument should be the AES Crypt binary"
    exit 1
fi

# Ensure the executable binary exists (and is executable)
if [ ! -x "$AESCRYPT" ] ; then
    echo "AES Crypt executable not found: $AESCRYPT"
    exit 1
fi

# Switch directories to where the test process resides
cd $( dirname "${BASH_SOURCE[0]}" ) || exit 1

# Attempt to encrypt a directory (this should fail)
result_text=$("$AESCRYPT" -q -e -p secret -o /dev/null /etc 2>&1)
exit_code=$?

if [ $exit_code -eq 0 ] ; then
    echo "Attempt to encrypt a directory should have failed"
    exit 1
fi

if [[ "$result_text" != "Input name is not a file: /etc" ]] ; then
    echo "Unexpected output: $result_text"
    exit 1
fi

# Attempt to encrypt a file writing into a directory (this should fail)
result_text=$("$AESCRYPT" -q -e -p secret -o /tmp /etc/passwd 2>&1)
exit_code=$?

if [ $exit_code -eq 0 ] ; then
    echo "Attempt to encrypt output to a directory should have failed"
    exit 1
fi

if [[ "$result_text" != "Target output cannot be a directory: /tmp" ]] ; then
    echo "Unexpected output: $result_text"
    exit 1
fi

# Attempt to decrypt a directory (this should fail)
result_text=$("$AESCRYPT" -q -d -p secret -o /dev/null /etc 2>&1)
exit_code=$?

if [ $exit_code -eq 0 ] ; then
    echo "Attempt to encrypt a directory should have failed"
    exit 1
fi

if [[ "$result_text" != "Input name is not a file: /etc" ]] ; then
    echo "Unexpected output: $result_text"
    exit 1
fi

# Attempt to decrypt a file writing into a directory (this should fail)
result_text=$("$AESCRYPT" -q -d -p secret -o /tmp /etc/passwd 2>&1)
exit_code=$?

if [ $exit_code -eq 0 ] ; then
    echo "Attempt to decrypt output to a directory should have failed"
    exit 1
fi

if [[ "$result_text" != "Target output cannot be a directory: /tmp" ]] ; then
    echo "Unexpected output: $result_text"
    exit 1
fi
